name: Publish 

on: [push]

jobs:
  job_1:
    name: x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cross
      - run: cross build --target x86_64-unknown-linux-musl --release
      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-unknown-linux-musl 
          path: target/x86_64-unknown-linux-musl/release/grafana-materialize-datasource

  job_2:
    name: aarch64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cross
      - run: cross build --target aarch64-unknown-linux-musl --release
      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-unknown-linux-musl 
          path: target/arch64-unknown-linux-musl/release/grafana-materialize-datasource

  job_3:
    name: Display results
    needs: [job_1, job_2]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: aarch64-unknown-linux-musl 
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-musl 
